// Employer logs in.
// User presses button on landing page.
// User is redirecting to a page where they can enter all necessary information about their post.
// a. If user does not enter all info and clicks , then error message shows up.
// User clicks on button.
// User gets redirected to the landing page and gets notification that their job-posting was added.
import { login, enterValueInInputEmployerForm, enterValueInTextAreaEmployerForm, enterValueInMatSelectEmployerForm, enterValueInMatOptionEmployerForm } from './utils.cy'
describe('Employer Logs In', () => {
    it('Enters Credentials of a Student', () => {
      login('isaczu15@gmail.com', 'soen341')
      })

      it('Redirects to Landing Page, checks if is Employer', () => {
        login('isaczu15@gmail.com', 'soen341')
        cy.url().should('eq', 'http://localhost:4200/') 
        cy.get('nav')
          .find('#myDIV')
          .find('ul')
          .find('li')
          .eq(2)
          .contains('Create New Posting')
          cy.get('app-landing')
          .should('exist')
      })
      it('Employer clicks on "Create New Posting"', () => {
        login('isaczu15@gmail.com', 'soen341')
        cy.url().should('eq', 'http://localhost:4200/') 
        cy.get('nav')
          .find('#myDIV')
          .find('ul')
          .find('li')
          .eq(2)
          .click()
          cy.url().should('eq', 'http://localhost:4200/employer-form') 

      })
      it('Employer fills up form without Image"', () => {
        login('isaczu15@gmail.com', 'soen341')
        cy.url().should('eq', 'http://localhost:4200/') 
        cy.get('nav')
          .find('#myDIV')
          .find('ul')
          .find('li')
          .eq(2)
          .click()
          cy.url().should('eq', 'http://localhost:4200/employer-form') 
          enterValueInInputEmployerForm(0, 'Cypress Tester')
          enterValueInInputEmployerForm(1, 'New York')
          enterValueInMatSelectEmployerForm(0)
          enterValueInMatOptionEmployerForm(0)
          enterValueInInputEmployerForm(2, '30$/hour')
          enterValueInInputEmployerForm(3, '8 months')
          enterValueInInputEmployerForm(4, 'Ann-Marie Czuboka')
          enterValueInTextAreaEmployerForm(0, 'Testing with Cypress')
          enterValueInTextAreaEmployerForm(1, 'No requirements')
          enterValueInInputEmployerForm(5, '01/05/2023')
          cy.get('mat-form-field') 
            .eq(9)
            .find('mat-select')
            .eq(0)
            .click({ force: true })         
        enterValueInMatOptionEmployerForm(1)
          cy.get('mat-form-field') 
            .eq(10)
            .find('mat-select')
            .eq(0)
            .click({ force: true }) 
        enterValueInMatOptionEmployerForm(1)
        enterValueInInputEmployerForm(6, 'Isabelle')
        enterValueInInputEmployerForm(7, 'Czuboka')
        enterValueInInputEmployerForm(8, 'www.twins.com')
        enterValueInInputEmployerForm(9, 'Montreal')
        enterValueInInputEmployerForm(10, 'Quebec')
        enterValueInInputEmployerForm(11, 'H9J 3B4')
        // const p = '/Users/ann-marieczuboka/Documents/SOEN 341/2Squared-soen341project2023/cypress/fixtures/Images/photo-1498050108023-c5249f4df085.png'
        // cy.get('input')
        //     .eq(12)
        //     .selectFile(p, {force:true})
        cy.get('app-employer-form')
            .find('button')
            .eq(1)
            .click( { force: true} )
        cy.get('.mat-mdc-snack-bar-label')
        .should('exist')
        // cy.get('app-nav')
        //     .find('nav')
        //     .find('a')
        //     .contains('Job Hunting Application')
        //     .click({ force: true })
        // cy.url().should('eq', 'http://localhost:4200/#!') 
        // cy.wait(3000)
        // cy.get('app-landing')
        // .find('app-job-post')
        // .find('app-search')
        // .find('mat-label')
        // .should('contain', 'Search by position, title or company')
        // cy.get('app-search')
        //     .click()
        //     .type('Cypress Tester')
        // cy.get('app-landing')
        //     .find('app-job-post')
        //     .eq(0)
        //     .find('.top-card')
        //     .find('p')
        //     .should('contain', 'Cypress Tester')
       
      })

  })

  